### ISSUE TITLE
main.less

### ISSUE THREAD

**Issue by iarico** [inuitless/inuit.css#5] opened 2013-05-28 09:12 UTC
main.less is compiling strangely. I don't know enough about LESS to know why. I'm not sure if this is a bug or my error.

This is the output I'm getting to style.css from mail.less

```
font: 1em / 1.5 [object Object],[object Object],[object Object];
```

**Comment by peterwilsoncc** [comment] 2013-05-28 12:43
I'll take a look this weekend. 

Are you able to attach your vars file to this issue too. 

##

**Comment by nicoespeon** [comment] 2013-05-28 14:51
The problem seems to come from the [base/main.less](https://github.com/peterwilsoncc/inuit.css/blob/LESS/base/main.less) file.

Basically, the font for **html** is defined this way:

``` css
html{
    font: e(%("%d / %d %s", (@base-font-size/16)*1em, @line-height-ratio, @base-font-family));
    ...
```

It works fine... excepted when you just try to change the `@base-font-family` for something different which is not a string.

For instance, this will produce the error spotted:

``` css
@base-font-family:    'Roboto', sans-serif;
```

To compile correctly, I've to change it for:

``` css
@base-font-family:    e(%("'%s', %s", 'Roboto', sans-serif));
```

This looks a bit weird, I'll try to figure out how to fix it.

**Comment by nicoespeon** [comment] 2013-05-31 06:19
Well I figured out precisely what the problem came from and how to fix it.

The problem is due to the fact that, if you declare your variable just like you declare your `font-family` property, you're doing it wrong because it's not a string anymore, but a list of objects:

``` css
@base-font-family:    'Roboto', sans-serif;     // This is a list of object
@base-font-family:    "'Roboto', sans-serif";   // This is a string
```

As the variable is compile, it needs to be a string to render properly. So the first method is not the good one and you have to make it a string!

Note that you don't have to use my weird syntax however:

``` css
// These are equivalents
@base-font-family:    e(%("'%s', %s", 'Roboto', sans-serif));
@base-font-family:    "'Roboto', sans-serif";
```

This is not an issue in SASS as it handles correctly the string, but LESS has more trouble with this.

Instead to add comments to make people not forget to declare a string (which would not be instinctive), I'll just change the way the variable is handle in the `html` declaration to make it works at anytime.

I'll close this issue once corrected, thanks @TheLoneCuber for pointing that out!

**Closed as completed** 2013-05-31 06:27 UTC
